- hosts: all
  become: yes

  tasks:
    - name: Add snap to path
      blockinfile:
        path: "/home/vagrant/.bashrc"
        content: |
          # Juju
          alias watch-juju='watch --color -n1 juju status --color'
          # Add snaps to path
          export PATH=/snap/bin:$PATH

    - name: Install zfs
      apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - zfs
        - snapcraft

    - name: Install lxd
      apt:
        name: "{{ item }}"
        state: latest
        default_release: xenial-backports
      with_items:
        - lxd
        - lxd-client

    - name: Setup lxd
      command: "{{ item }}" 
      with_items:
        - lxd init --auto --storage-backend zfs --storage-create-loop 30 --storage-pool lxd
        - lxc network create lxdbr0
        - lxc network attach-profile lxdbr0 default eth0
        - lxc network set lxdbr0 ipv6.address none
      ignore_errors: yes

    - name: Install core snap
      command: snap install core
